import os
import logging
from pathlib import Path
from typing import Dict, Any
from config import settings

logger = logging.getLogger("IdeationGOAT.Scaffolder")

class ScaffoldSecurityError(PermissionError):
    """Raised when trying to write outside the permitted workspace directory."""
    pass

class ProjectScaffolder:
    """
    Secure file scaffolding system that guards against path traversal
    and generates standard code boilerplates in the workspace.
    """
    
    @staticmethod
    def validate_path(target_path: Path, root_path: Path = settings.WORKSPACE_ROOT) -> Path:
        """
        Validates target path against root path to prevent path traversal attacks.
        """
        resolved_target = target_path.resolve()
        resolved_root = root_path.resolve()
        
        # Verify that the target is a subdirectory of the allowed root
        if not str(resolved_target).startswith(str(resolved_root)):
            raise ScaffoldSecurityError(
                f"Security Violation: Target path '{resolved_target}' "
                f"is outside the allowed workspace root '{resolved_root}'."
            )
        return resolved_target

    def scaffold(self, synthesis_output: Dict[str, Any], project_directory: str) -> Dict[str, Any]:
        """
        Generates file scaffolds inside the target folder securely.
        """
        try:
            target_dir = Path(project_directory)
            validated_dir = self.validate_path(target_dir)
        except ScaffoldSecurityError as se:
            logger.error(f"Path validation security failure: {str(se)}")
            return {"status": "error", "message": str(se)}
            
        logger.info(f"Scaffolding project inside validated directory: {validated_dir}")
        os.makedirs(validated_dir, exist_ok=True)
        
        payload = synthesis_output.get("synthesis_payload", {})
        p_name = payload.get("paradigm_name", "Cross-Domain Hybrid Prototype")
        bridge = payload.get("structural_bridge", "No bridge data available.")
        mechanics = payload.get("hybrid_mechanics", "No operational mechanics specified.")
        math_formula = payload.get("mathematical_grafting_formula", "S_c = f(A, B)")
        tradeoffs = payload.get("critical_tradeoffs", [])
        
        tradeoffs_md = "\n".join([f"* **Risk:** {t}" for t in tradeoffs])
        
        written_files = []
        try:
            # 1. Write README.md
            readme_path = validated_dir / "README.md"
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(f"""# {p_name.upper()}

## Conceptual Bridge
{bridge}

## Operational Mechanics
{mechanics}

## Mathematical Foundation
$${math_formula}$$

## System Risks
{tradeoffs_md}

---
*Generated by Ideation GOAT Scaffolder.*
""")
            written_files.append("README.md")
            
            # 2. Write math_engine.py
            engine_path = validated_dir / "math_engine.py"
            with open(engine_path, "w", encoding="utf-8") as f:
                f.write(f'''"""
Mathematical Engine for {p_name}
Formula: {math_formula}
"""
import math
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("MathEngine")

def calculate_graft_metrics(v_a: list, v_b: list, delta_t: float, gamma: float = 0.95) -> float:
    """
    Computes convergence/decay across distinct domain spaces.
    LaTeX Formula: {math_formula}
    """
    logger.info("Initializing convergence calculations.")
    try:
        dot_product = sum(a * b for a, b in zip(v_a, v_b))
        decay_factor = math.pow(gamma, delta_t)
        score = dot_product * decay_factor
        return score
    except Exception as e:
        logger.error(f"Error during calculation loop: {{e}}")
        return 0.0
''')
            written_files.append("math_engine.py")
            
            # 3. Write state_buffer.py
            buffer_path = validated_dir / "state_buffer.py"
            with open(buffer_path, "w", encoding="utf-8") as f:
                f.write(f'''"""
State Buffer & Eviction Registry for {p_name}
"""
import time
from typing import Dict, Any, Optional

class StateBuffer:
    """
    Non-blocking state storage structure utilizing dynamic eviction rules.
    """
    def __init__(self):
        self.registry: Dict[str, Any] = {{}}
        self.write_rates: Dict[str, float] = {{}}
        
    def register_state(self, key: str, payload: Any):
        """
        Saves key payload and increments local traffic density coordinates.
        """
        self.registry[key] = payload
        self.write_rates[key] = self.write_rates.get(key, 0.0) + 1.0
        
    def check_eviction(self) -> Optional[str]:
        """
        Determines eviction candidate based on dynamic thresholds.
        """
        if not self.registry:
            return None
        candidate = min(self.write_rates, key=self.write_rates.get)
        return candidate
''')
            written_files.append("state_buffer.py")
            
            # 4. Write requirements.txt
            req_path = validated_dir / "requirements.txt"
            with open(req_path, "w", encoding="utf-8") as f:
                f.write("pydantic>=2.0.0\n")
            written_files.append("requirements.txt")
            
            # 5. Generate Docker scaffolding ("Works Anywhere" Synthesizer)
            # Detect language/framework from imports or paradigm names
            framework = "python"
            p_name_lower = p_name.lower()
            if any(k in p_name_lower for k in ["express", "node", "nest", "next", "react", "vue"]):
                framework = "node"
            elif any(k in p_name_lower for k in ["axum", "actix", "rust"]):
                framework = "rust"
            elif any(k in p_name_lower for k in ["gin", "fiber", "go"]):
                framework = "go"
                
            docker_files = self.generate_docker_files(validated_dir, framework)
            written_files.extend(docker_files)
            
            return {
                "status": "success",
                "scaffold_directory": str(validated_dir),
                "files_created": [
                    "README.md",
                    "math_engine.py",
                    "state_buffer.py",
                    "requirements.txt",
                    "Dockerfile",
                    "docker-compose.yml",
                    ".env.example"
                ],
                "instruction": "Open the directory in your workspace and run docker-compose up to start your environment."
            }
        except Exception as e:
            logger.error(f"Scaffolding operation failed midway: {str(e)}")
            # Rollback: Clean up partially written files
            for f_name in written_files:
                try:
                    os.remove(validated_dir / f_name)
                except Exception:
                    pass
            return {"status": "error", "message": f"Scaffolding failed: {str(e)}"}

    def generate_docker_files(self, validated_dir: Path, target_framework: str) -> list:
        """
        Generates Dockerfile, docker-compose.yml, and .env.example configuration files.
        """
        target_framework = target_framework.lower().strip()
        dockerfile_content = ""
        
        # 1. Generate Dockerfile based on framework/language
        if target_framework == "node":
            dockerfile_content = """# Build Stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build --if-present

# Production Stage
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["npm", "start"]
"""
        elif target_framework == "rust":
            dockerfile_content = """# Build Stage
FROM rust:1.75-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src/ ./src/
RUN cargo build --release

# Production Stage
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/app-binary ./app-binary
EXPOSE 8080
CMD ["./app-binary"]
"""
        elif target_framework == "go":
            dockerfile_content = """# Build Stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app-binary .

# Production Stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/app-binary .
EXPOSE 8080
CMD ["./app-binary"]
"""
        else:  # Default to Python
            dockerfile_content = """# Build Stage
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Production Stage
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /root/.local /root/.local
COPY . .
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["python", "math_engine.py"]
"""

        # 2. Generate docker-compose.yml
        compose_content = """version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
"""

        # 3. Generate .env.example
        env_content = """# App Configuration
PORT=8080
NODE_ENV=development

# Database configuration
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/db_name

# Security Auth settings
API_KEY=your_sandbox_api_key_goes_here
"""

        # Write files
        with open(validated_dir / "Dockerfile", "w", encoding="utf-8") as f:
            f.write(dockerfile_content)
        with open(validated_dir / "docker-compose.yml", "w", encoding="utf-8") as f:
            f.write(compose_content)
        with open(validated_dir / ".env.example", "w", encoding="utf-8") as f:
            f.write(env_content)
            
        return ["Dockerfile", "docker-compose.yml", ".env.example"]
